### ISSUE TITLE
imitate clipboard under WSL by clip.exe

### ISSUE THREAD

**Issue by Konfekt** [Jorengarenar/fauxClip#2]
How about adding a check for the executability of `clip.exe` which makes it possible to use the Windows clipboard under WSL which is lacking by default. [Here](https://stackoverflow.com/a/58822884) are some mappings I came up with instead, but linking to this plug-in seems like the cleanest cure.

**Comment by Jorengarenar** [comment]
I have no means to check whether it works, so if you would be so kind and test it for me?

**Comment by Konfekt** [comment]
Thanks! Today my WSL notebook is not with me, but as a first remark, for pasting `xclip` instead of `paste.exe` is fine, as pasting is done in WSL which is a Linux terminal. Only copying to the Windows clipboard needs `clip.exe`. `Paste.exe` could be interesting for Windows Vim.
